In [1]:
import pandas as pd
import numpy as np
from __future__ import print_function
import time
import cfbd
from cfbd.rest import ApiException
from pprint import pprint
import pandas as pd
from pandas.io.json import json_normalize
import json
import numpy as np
from datetime import datetime

In [2]:
# Configure API key authorization: ApiKeyAuth
configuration = cfbd.Configuration()
configuration.api_key['Authorization'] = 'RRRpRRQDqVoLX6S9Oivl7G9fXmZ/4TDcL9q+xg6pBW+yWfU1PIrYm/cbwKVuIfwn'
configuration.api_key_prefix['Authorization'] = 'Bearer'

In [3]:
#Week 1

In [4]:
api_instance = cfbd.GamesApi(cfbd.ApiClient(configuration))
games = api_instance.get_team_game_stats(year=2021,week=1)
game_stats_df = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[0].school,stat=s.category,value=s.stat) for g in games for s in g.teams[0].stats])
game_stats_df1 = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[1].school,stat=s.category,value=s.stat) for g in games for s in g.teams[1].stats])
game_stats_w1 = pd.concat([game_stats_df,game_stats_df1],axis=0)

In [5]:
#Week 2

In [6]:
api_instance = cfbd.GamesApi(cfbd.ApiClient(configuration))
games = api_instance.get_team_game_stats(year=2021,week=2)
game_stats_df = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[0].school,stat=s.category,value=s.stat) for g in games for s in g.teams[0].stats])
game_stats_df1 = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[1].school,stat=s.category,value=s.stat) for g in games for s in g.teams[1].stats])
game_stats_w2 = pd.concat([game_stats_df,game_stats_df1],axis=0)

In [7]:
#Week 3

In [8]:
api_instance = cfbd.GamesApi(cfbd.ApiClient(configuration))
games = api_instance.get_team_game_stats(year=2021,week=3)
game_stats_df = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[0].school,stat=s.category,value=s.stat) for g in games for s in g.teams[0].stats])
game_stats_df1 = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[1].school,stat=s.category,value=s.stat) for g in games for s in g.teams[1].stats])
game_stats_w3 = pd.concat([game_stats_df,game_stats_df1],axis=0)

In [9]:
#Week 4

In [10]:
api_instance = cfbd.GamesApi(cfbd.ApiClient(configuration))
games = api_instance.get_team_game_stats(year=2021,week=4)
game_stats_df = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[0].school,stat=s.category,value=s.stat) for g in games for s in g.teams[0].stats])
game_stats_df1 = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[1].school,stat=s.category,value=s.stat) for g in games for s in g.teams[1].stats])
game_stats_w4 = pd.concat([game_stats_df,game_stats_df1],axis=0)

In [11]:
#Week 5

In [12]:
api_instance = cfbd.GamesApi(cfbd.ApiClient(configuration))
games = api_instance.get_team_game_stats(year=2021,week=5)
game_stats_df = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[0].school,stat=s.category,value=s.stat) for g in games for s in g.teams[0].stats])
game_stats_df1 = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[1].school,stat=s.category,value=s.stat) for g in games for s in g.teams[1].stats])
game_stats_w5 = pd.concat([game_stats_df,game_stats_df1],axis=0)

In [13]:
#Week 6

In [14]:
api_instance = cfbd.GamesApi(cfbd.ApiClient(configuration))
games = api_instance.get_team_game_stats(year=2021,week=6)
game_stats_df = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[0].school,stat=s.category,value=s.stat) for g in games for s in g.teams[0].stats])
game_stats_df1 = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[1].school,stat=s.category,value=s.stat) for g in games for s in g.teams[1].stats])
game_stats_w6 = pd.concat([game_stats_df,game_stats_df1],axis=0)

In [15]:
#Week 7

In [16]:
api_instance = cfbd.GamesApi(cfbd.ApiClient(configuration))
games = api_instance.get_team_game_stats(year=2021,week=7)
game_stats_df = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[0].school,stat=s.category,value=s.stat) for g in games for s in g.teams[0].stats])
game_stats_df1 = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[1].school,stat=s.category,value=s.stat) for g in games for s in g.teams[1].stats])
game_stats_w7 = pd.concat([game_stats_df,game_stats_df1],axis=0)

In [17]:
#Week 8

In [18]:
api_instance = cfbd.GamesApi(cfbd.ApiClient(configuration))
games = api_instance.get_team_game_stats(year=2021,week=8)
game_stats_df = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[0].school,stat=s.category,value=s.stat) for g in games for s in g.teams[0].stats])
game_stats_df1 = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[1].school,stat=s.category,value=s.stat) for g in games for s in g.teams[1].stats])
game_stats_w8 = pd.concat([game_stats_df,game_stats_df1],axis=0)

In [19]:
#Week 9

In [20]:
api_instance = cfbd.GamesApi(cfbd.ApiClient(configuration))
games = api_instance.get_team_game_stats(year=2021,week=9)
game_stats_df = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[0].school,stat=s.category,value=s.stat) for g in games for s in g.teams[0].stats])
game_stats_df1 = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[1].school,stat=s.category,value=s.stat) for g in games for s in g.teams[1].stats])
game_stats_w9 = pd.concat([game_stats_df,game_stats_df1],axis=0)

In [21]:
#Week 10

In [22]:
api_instance = cfbd.GamesApi(cfbd.ApiClient(configuration))
games = api_instance.get_team_game_stats(year=2021,week=10)
game_stats_df = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[0].school,stat=s.category,value=s.stat) for g in games for s in g.teams[0].stats])
game_stats_df1 = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[1].school,stat=s.category,value=s.stat) for g in games for s in g.teams[1].stats])
game_stats_w10 = pd.concat([game_stats_df,game_stats_df1],axis=0)

In [23]:
#Week 11

In [24]:
api_instance = cfbd.GamesApi(cfbd.ApiClient(configuration))
games = api_instance.get_team_game_stats(year=2021,week=11)
game_stats_df = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[0].school,stat=s.category,value=s.stat) for g in games for s in g.teams[0].stats])
game_stats_df1 = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[1].school,stat=s.category,value=s.stat) for g in games for s in g.teams[1].stats])
game_stats_w11 = pd.concat([game_stats_df,game_stats_df1],axis=0)

In [25]:
#Week 12

In [26]:
api_instance = cfbd.GamesApi(cfbd.ApiClient(configuration))
games = api_instance.get_team_game_stats(year=2021,week=12)
game_stats_df = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[0].school,stat=s.category,value=s.stat) for g in games for s in g.teams[0].stats])
game_stats_df1 = pd.DataFrame.from_records([dict(id = g.id,school=g.teams[1].school,stat=s.category,value=s.stat) for g in games for s in g.teams[1].stats])
game_stats_w12 = pd.concat([game_stats_df,game_stats_df1],axis=0)

In [27]:
game_stats_df_2021 = pd.concat([game_stats_w1,game_stats_w2,game_stats_w3,game_stats_w4,game_stats_w5,game_stats_w6,game_stats_w7,game_stats_w8,game_stats_w9,game_stats_w10,game_stats_w11,game_stats_w12],axis=0)

In [28]:
game_stats_df_2021.head()

          id         school             stat value
0  401282614  Florida State       rushingTDs     3
1  401282614  Florida State       passingTDs     2
2  401282614  Florida State  kickReturnYards    72
3  401282614  Florida State    kickReturnTDs     0
4  401282614  Florida State      kickReturns     3

In [29]:
game_stats_df_pivot = pd.pivot_table(data=game_stats_df_2021,index=['id','school'],columns='stat',values='value',aggfunc='first')
game_stats_2021 = game_stats_df_pivot.reset_index(drop=False)

In [30]:
game_stats_2021[game_stats_2021['school']=='Michigan']

stat,id,school,completionAttempts,defensiveTDs,firstDowns,fourthDownEff,fumblesLost,fumblesRecovered,interceptionTDs,interceptionYards,...,sacks,tackles,tacklesForLoss,thirdDownEff,totalFumbles,totalPenaltiesYards,totalYards,turnovers,yardsPerPass,yardsPerRushAttempt
623,401282727,Michigan,15-28,0,19,1-1,0,1,NaN,NaN,...,2,24,3,3-12,0,5-35,411,1,8.0,4.9
663,401282770,Michigan,29-40,2,24,1-3,0,0,1,42,...,2,56,4,7-13,2,6-50,503,0,8.8,4.3
666,401282772,Michigan,13-17,0,22,1-1,0,0,NaN,NaN,...,1,42,3,8-13,1,5-48,551,0,12.7,7.8
668,401282773,Michigan,7-15,0,20,2-3,0,1,NaN,NaN,...,4,35,7,7-16,1,6-60,387,0,2.9,6.1
670,401282774,Michigan,12-17,0,28,1-3,0,0,0,27,...,1,31,4,3-6,1,5-45,606,0,13.7,7.8
672,401282775,Michigan,9-16,0,15,0-0,0,2,NaN,NaN,...,1,49,6,4-11,0,6-59,275,0,10.2,2.9
674,401282776,Michigan,18-30,0,15,4-5,0,2,0,3,...,6,30,7,6-19,1,3-10,365,1,8.4,2.5
676,401282777,Michigan,31-48,0,26,1-3,1,0,0,5,...,3,33,3,8-17,3,8-59,552,2,8.5,4.3
678,401282778,Michigan,22-39,0,26,0-0,0,1,0,0,...,1,29,4,6-15,1,6-55,459,1,6.5,4.9
680,401282779,Michigan,23-32,0,28,1-1,2,1,0,23,...,1,27,4,12-20,2,4-40,457,2,5.1,5.4
682,401282780,Michigan,19-29,0,21,1-2,1,1,NaN,NaN,...,7,38,12,6-15,1,4-20,361,1,7.5,3.5

In [31]:
game_stats_2021.to_csv('game_stats_2021.csv')